### ISSUE TITLE
How to use your FuzzSlice

### ISSUE THREAD

**Issue by Crspidey** [NobleMathews/FuzzSliceICSE#2]
Hello Dear Author. I am a lower grade student and my teacher recommended this paper and asked me to try out this tool. Here are a few questions I would like to ask:
1、Can I only test projects built in C and using makefile?
2, projects placed in /test_lib/ don't need to be built, right?
3, what will be your follow-up work?
4, Which static analysis tool is more suitable for your fuzzslice?
Looking forward to your reply, thank you!

**Comment by Crspidey** [comment]
BTW, I have successfully configured fuzzslice and managed to find one false positive and two segv crashes from those three static analysis results from tmux. this proves that your fuzzslice is useful.

**Comment by Crspidey** [comment]
Wait, no need to reply yet. I'll read your FuzzSlice Technical Documentation and ask you if I don't understand anything.

**Comment by NobleMathews** [comment]
Hello there!

I'm glad to hear that your teacher recommended our paper and that you're interested in trying out our tool. Here are the answers to your questions:

- Yes, currently our focus is on projects built in C using makefiles. We expect the repository to be set up in a way that allows you to simply run "make all" to build it in the environment.

- You only need to setup the projects you want to test. The ones in /test_lib/ are examples we used in our paper. If you wish to run a different project, please set it up as outlined in our technical documentation for a new project.

- Our next steps primarily would involve extending the project to work with more types of projects

- We are currently using reports from RATS and Infer for static analysis. You can use any tools that present targets in the format we require, as mentioned in the technical documentation. Experimenting with other tools is part of our future plans.

I hope this helps!

**Comment by Crspidey** [comment]
> Hello there!
> 
> I'm glad to hear that your teacher recommended our paper and that you're interested in trying out our tool. Here are the answers to your questions:
> 
> * Yes, currently our focus is on projects built in C using makefiles. We expect the repository to be set up in a way that allows you to simply run "make all" to build it in the environment.
> * You only need to setup the projects you want to test. The ones in /test_lib/ are examples we used in our paper. If you wish to run a different project, please set it up as outlined in our technical documentation for a new project.
> * Our next steps primarily would involve extending the project to work with more types of projects
> * We are currently using reports from RATS and Infer for static analysis. You can use any tools that present targets in the format we require, as mentioned in the technical documentation. Experimenting with other tools is part of our future plans.
> 
> I hope this helps!

Dear Author, another question,where can I find the Fuzzing wrapper file generated in step 4?I've read that document and it only states that the slices are stored in the workspace/program_name/test_files directory.Thank you.

**Comment by NobleMathews** [comment]
The outer files you find in the workspace/program_name directory will have the fuzzing wrapper in it

**Comment by Crspidey** [comment]
> The outer files you find in the workspace/program_name directory will have the fuzzing wrapper in it

![1705542913886](https://github.com/NobleMathews/FuzzSliceICSE/assets/51468842/5c6daace-c424-4a2c-935e-1962c76928a9)
I did a test on enscript-3.09 using your tool and it is compliant with the project requirements, but there is a problem with the link. I am doing it separately in that container ，and
 . /configure    make     make install        is ok.   Also I can use enscript instruction to do something.

**Comment by Crspidey** [comment]
Maybe I need to make changes to main.py.

**Comment by Crspidey** [comment]
![1705627655383](https://github.com/NobleMathews/FuzzSliceICSE/assets/51468842/1cf902f1-ea0b-4c0a-a0ee-47429624d149)
What do you think is the reason for this error?I have downloaded all the files needed for libSM. Normal installation is fine.

**Comment by NobleMathews** [comment]
It looks like you might be using an outdated pickle file from when your build was unsuccessful, delete the previous cached data using the following commands from the project root and rerun your analysis (You can also delete only files pertaining to your project instead of the wildcard used below)

```
rm -rf test_lib/*/build_ss
rm -rf info_lib/*/build_logs*
rm -rf info_lib/*/srcml.xml
rm info_lib/{project_name}/{project_name}
```

**Comment by Crspidey** [comment]
I used fuzzslice to make a false positive determination for libSM-1.2.4 at a location I set myself, and the result was surprisingly TRUE POSITIVE. it looks like I'll need to do a bit of static analysis of libSM with RATS.

> It looks like you might be using an outdated pickle file from when your build was unsuccessful, delete the previous cached data using the following commands from the project root and rerun your analysis (You can also delete only files pertaining to your project instead of the wildcard used below)
> 
> ```
> rm -rf test_lib/*/build_ss
> rm -rf info_lib/*/build_logs*
> rm -rf info_lib/*/srcml.xml
> rm info_lib/{project_name}/{project_name}
> ```

I used fuzzslice to make a false positive determination for libSM-1.2.4 at a location I set myself, and the result was surprisingly TRUE POSITIVE. it looks like I'll need to do a bit of static analysis of libSM with RATS.Haha.

**Comment by Crspidey** [comment]
> It looks like you might be using an outdated pickle file from when your build was unsuccessful, delete the previous cached data using the following commands from the project root and rerun your analysis (You can also delete only files pertaining to your project instead of the wildcard used below)
> 
> ```
> rm -rf test_lib/*/build_ss
> rm -rf info_lib/*/build_logs*
> rm -rf info_lib/*/srcml.xml
> rm info_lib/{project_name}/{project_name}
> ```
![1705633579453](https://github.com/NobleMathews/FuzzSliceICSE/assets/51468842/a37e8179-6597-444e-a076-9cda135eeb4a)

I used fuzzslice to make a false positive determination for libSM-1.2.4 at a location I set myself, and the result was surprisingly TRUE POSITIVE. it looks like I'll need to do a bit of static analysis of libSM with RATS.Haha

**Comment by Crspidey** [comment]
I feel that it is more intended for developers' use, facilitating their collaboration in clearing false positives and quickly pinpointing true positives.Right?
