### ISSUE TITLE
some  questions

### ISSUE THREAD

**Issue by Crspidey** [NobleMathews/FuzzSliceICSE#3]
Dear author, I have tested libedit and libSM using fuzzslice tool and I have encountered a few problems I hope to get your reply
First problem:
Both run with this problem: fatal error: '/StaticSlicer/test_lib/libedit/config.h' file not found. in fact, on my own linux VM running . /configure and make commands, the config.h file exists, but when I run the python3 main.py command in docker, this error pops up.
Second problem:
Traceback (most recent call last).
  File "main.py", line 1232, in <module
    analyze(lib_srcml, [issue])
  File "main.py", line 692, in analyze
    func, concat_locations = minimize_target(srcml, issue)
  File "main.py", line 533, in minimize_target
    concat_locations = handle_missing_links(issue, lib_src)
  File "main.py", line 563, in handle_missing_links
    compile_command, linker_locs, additional_linker = logs.get_compile_dependencies(
  File "/StaticSlicer/build_log_parser.py", line 710, in get_compile_dependencies
    compile_detail = all_compiles_encountered[0]
IndexError: list index out of range

**Comment by Crspidey** [comment]
Third question:
What should I do with the possible true positives reported by fuzzslice, and what should I do with them?
Fourth question:
The error type reported by infer does not match the crash reason reported by libfuzzer. Also, how do I find the crashfiles generated by libfuzzer?

I have become proficient in using tools like AFL++ to find multiple vulnerabilities and get multiple CVE numbers. To target the library I need to use libfuzzer, but I'm not very good at writing a fuzz target for libfuzzer, I've searched for this tool of yours so I want to become proficient with it and get help for my vulnerability mining. I'm sorry for disturbing you.

**Comment by NobleMathews** [comment]
Sorry, we missed your ticket. Have been busy the past few months on other projects. Please reopen if required.
